stages:
  - test
  - build
  - deploy

variables:
  MONGO_URL: fake

# Run flake8 to check for code quality
# lint-test-job:
#   image: python:3-bullseye
#   stage: test
#   script:
#     - pip install flake8
#     - flake8 game_night

# Run the unit tests
api-unit-test-job:
  image: python:3-bullseye
  stage: test
#   needs:
#     - lint-test-job
  script:
    - cd game_night
    - pip install -r requirements.txt
    - python -m pytest

# Build the React/JavaScript front-end
build-front-end-job:
  rules:
    # Only run if pushing to the main branch
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  stage: build
  image: node:lts-bullseye
  needs:
    # - lint-test-job
    - api-unit-test-job
  variables:
    # If either of these variables is defined in the GitLab
    # CI/CD variables, that value will override the value here.
    # You need to substitute in your real values for
    # GROUP_NAME, PROJECT_NAME, & WEBSERVICE_NAME below.
    PUBLIC_URL: https://M2J3.gitlab.io/game-night-planner
    REACT_APP_SAMPLE_SERVICE_API_HOST: https://game-night-planner.onrender.com
  script:
    - cd ghi
    - npm install
    - npm run build
    - cp build/index.html build/404.html
  artifacts:
    paths:
      - ghi/build/

# build-fastapi-image-job:
#   rules:
#     # Only run if pushing to the main branch
#     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#   stage: build

# Deploy the React/JavaScript front-end to GitLab pages
pages:
  stage: deploy
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  dependencies:
    - build-front-end-job
  needs:
    - build-front-end-job
  script:
    - mv ghi/build/ public
  artifacts:
    paths:
      - public
